modLoader="javafml"
loaderVersion="[32,)"
license="MIT License"
[[mods]]
modId="zombification"
version="${file.jarVersion}"
displayName="Zombification 100"
displayURL="https://github.com/Theta-Dev/Zombification100"
authors="ThetaDev"
description='''
Set the chance of a villager being zombified independent from the game difficulty.
'''
[[dependencies.zombification]]
modId="forge"
mandatory=true
versionRange="[32,)"
ordering="NONE"
side="BOTH"
[[dependencies.zombification]]
modId="minecraft"
mandatory=true
versionRange="[1.16.1, 1.17)"
ordering="NONE"
side="BOTH"
