modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="zombification"
version="${file.jarVersion}"
displayName="Zombification 100"
displayURL="https://github.com/Theta-Dev/Zombification100"
authors="ThetaDev"
description='''
Set the chance of a villager being zombified independent from the game difficulty.
'''
[[dependencies.zombification]]
modId="forge"
mandatory=true
versionRange="[31,)"
ordering="NONE"
side="BOTH"
[[dependencies.zombification]]
modId="minecraft"
mandatory=true
versionRange="[1.15.2]"
ordering="NONE"
side="BOTH"
